### PR TITLE
Add support for avy-all-windows

### PR DESCRIPTION
**Pull request by noctuid**
I'd like to be able to use evil-easymotion for multiple windows/frames at once. It may not be as useful for the normal motions easymotion creates which is why I have `evilem-all-windows` default to nil instead of the corresponding avy value. I can change this if you want. I think this functionality is nice, especially when calling the motion function from `(window-start)`.

### CODE REVIEW

**Comment by PythonNut** [comment]
I feel like this should be an option per-motion, `:all-windows t` maybe?

**Comment by noctuid** [comment]
Okay I updated the commit. Any other suggestions? Is it okay that I changed `evilem--collect` to use `cl-defun`?

**Comment by PythonNut** [comment]
The more I think about it, the more I feel like jumping between windows doesn't fall in `evil-easymotion`'s domain. For example, the concept of operating on a motion. What advantage is there to using `evil-easymotion` instead of just regular `avy` proper?

**Comment by noctuid** [comment]
The advantages are the same. `evil-easymotion` basically is avy with support for some convenient things like the hooks and choosing the scope, automatic key definition, and now allowing multiple motions. Multi-window support doesn't change any of that. It may not be that useful for most users, but I would use it personally.

**Comment by PythonNut** [comment]
Sorry for breaking the merge. :/

**Comment by noctuid** [comment]
> I'm not against using it, but I don't think it's needed right now.

Sure, I'll get rid of the global option then.

> Sorry for breaking the merge. :/

No problem; I'll fix it.

**Comment by noctuid** [comment]
Okay I fixed it; it will default to off. Thanks a lot for the package by the way. I've been using it a lot recently and think I'll make it an optional dependency in a few of my own packages.

**Comment by PythonNut** [comment]
After trying this out, I can honestly say that it's very strange. I can't think of any situation where I would use it. But if you can then sure. 

Thanks for the pull request!

**Pull request merged**
